language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-lt-frontside' ]; then cd .. && eval "mv $currentfolder generator-lt-frontside" && cd generator-lt-frontside; fi
